INSERT INTO sector values (1, 'Manufacturing');
INSERT INTO sector values (2, 'Construction materials');
INSERT INTO sector values (3, 'Electronics and Optics');
INSERT INTO sector values (4, 'Food and Beverage');
INSERT INTO sector values (5, 'confectionery products');
INSERT INTO sector values (6, 'Beverages');
INSERT INTO sector values (7, 'fish products');
INSERT INTO sector values (8, 'meat products');
INSERT INTO sector values (9, 'dairy products');
INSERT INTO sector values (10, 'Other');
INSERT INTO sector values (11, 'snack food');
INSERT INTO sector values (12, 'Furniture');
INSERT INTO sector values (13, 'Bathroom/sauna');
INSERT INTO sector values (14, 'Bedroom');
INSERT INTO sector values (15, 'Childrens Room');
INSERT INTO sector values (16, 'Kitchen');
INSERT INTO sector values (17, 'Living Room');
INSERT INTO sector values (18, 'Office');
INSERT INTO sector values (19, 'Other');
INSERT INTO sector values (20, 'Outdoor Project');
INSERT INTO sector values (21, 'Furniture');
INSERT INTO sector values (22, 'Machinery');
INSERT INTO sector values (23, 'Machinery components');
INSERT INTO sector values (24, 'Machinery Equipments');
INSERT INTO sector values (25, 'Manufacture of machinery');
INSERT INTO sector values (26, 'Maritime');
INSERT INTO sector values (27, 'Aluminium and steel workboats');
INSERT INTO sector values (28, 'Boat/Yacht building');
INSERT INTO sector values (29, 'Boat/Yacht building');
INSERT INTO sector values (30, 'Metal structures');
INSERT INTO sector values (31, 'Other');
INSERT INTO sector values (32, 'Repair and maintenance service');
INSERT INTO sector values (33, 'MetalWorking');
INSERT INTO sector values (34, 'Construction of metal structures');
INSERT INTO sector values (35, 'Houses and buildings');
INSERT INTO sector values (36, 'Metal products');
INSERT INTO sector values (37, 'Metal works');
INSERT INTO sector values (38, 'CNC-machining');
INSERT INTO sector values (39, 'Forgings, Fasteners');
INSERT INTO sector values (40, 'Gas, Plasma, Laser cutting');
INSERT INTO sector values (41, 'MIG, TIG, Aluminum welding');
INSERT INTO sector values (42, 'Plastic and Rubber');
INSERT INTO sector values (43, 'Packaging');
INSERT INTO sector values (44, 'Plastic goods');
INSERT INTO sector values (45, 'Plastic processing technology');
INSERT INTO sector values (46, 'Blowing');
INSERT INTO sector values (47, 'Moulding');
INSERT INTO sector values (48, 'Plastics welding and processing');
INSERT INTO sector values (49, 'Plastic profiles');
INSERT INTO sector values (50, 'Printing');
INSERT INTO sector values (51, 'Advertising');
INSERT INTO sector values (52, 'Book/Periodicals printing');
INSERT INTO sector values (53, 'Labelling and packaging printing');
INSERT INTO sector values (54, 'Textile and Clothing');
INSERT INTO sector values (55, 'Clothing');
INSERT INTO sector values (56, 'Textile');
INSERT INTO sector values (57, 'Wood');
INSERT INTO sector values (58, 'Other (Wood)');
INSERT INTO sector values (59, 'Wooden building materials');
INSERT INTO sector values (60, 'Wooden houses');
INSERT INTO sector values (61, 'Other');
INSERT INTO sector values (62, 'Creative industries');
INSERT INTO sector values (63, 'Energy technology');
INSERT INTO sector values (64, 'Environment');
INSERT INTO sector values (65, 'Service');
INSERT INTO sector values (66, 'Business services');
INSERT INTO sector values (67, 'Engineering');
INSERT INTO sector values (68, 'Information Technology and Telecommunications');
INSERT INTO sector values (69, 'Data processing, Web portals, E-marketing');
INSERT INTO sector values (70, 'Programming, Consultancy');
INSERT INTO sector values (71, 'Software');
INSERT INTO sector values (72, 'Transport and Logistics');
INSERT INTO sector values (73, 'Air');
INSERT INTO sector values (74, 'Rail');
INSERT INTO sector values (75, 'Road');
INSERT INTO sector values (76, 'Water');